### ISSUE TITLE
ValueError: Expected value argument (Tensor of shape (128, 512, 16, 16)) to be within the support (Real()) of the distribution Normal(loc: 0.0, scale: 1.0)

### ISSUE THREAD

**Issue by kdafnis** [GustavoVargasHakim/TTTFlow#1]
Hello,

Thank you for the great work. I am trying to reproduce the results of the paper and I am facing the following issue regarding the  Flow training:

After a few epochs I am getting the following error:

Traceback (most recent call last):
  File "/path/to/project/TTTFlow/main.py", line 129, in <module>
    experiment(args)
  File "/path/to/project/TTTFlow/main.py", line 83, in experiment
    loss = criterion_uns(target, z, log_det)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/project/TTTFlow/utils/misc.py", line 31, in neg_log_likelihood_2d
    log_likelihood_per_dim = target.log_prob(z) + log_det
                             ^^^^^^^^^^^^^^^^^^
  File "/home/kd/anaconda3/envs/tttflow/lib/python3.11/site-packages/torch/distributions/normal.py", line 79, in log_prob
    self._validate_sample(value)
  File "/home/kd/anaconda3/envs/tttflow/lib/python3.11/site-packages/torch/distributions/distribution.py", line 300, in _validate_sample
    raise ValueError(
ValueError: Expected value argument (Tensor of shape (128, 512, 16, 16)) to be within the support (Real()) of the distribution Normal(loc: 0.0, scale: 1.0), but found invalid values:
tensor([[[[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]],
          ....

I used the hyper-parameters as they are described in the paper.

**Comment by GustavoVargasHakim** [comment]
Hello, thank you so much for your interest in TTTFlow. 

This error is familiar to us, as we also encountered it sometimes, and it was really depending on the system. We will re-check the repository to try to improve the stability of the code, but for now we can recommend trying using Adam as the optimizer instead of SGD (for now, SGD is the default in the code). 

We will update the code as soon as possible. In the meantime, thank you for pointing out this issue.

**Comment by kdafnis** [comment]
Thank you very much for your response.

I tried to use Adam optimizer instead of SGD. Using Adam still gives me this error. Also, I tried to set the initial learning rate to 0.01, but still getting the error.

One other issue that I noticed is that, when I try to train the classification setting (only ResNet Backbone and main head) the Classification Error stays constant at 90% (using the default learning rate).

**Comment by XiaoLin-Jiao** [comment]
> Thank you very much for your response.
> 
> I tried to use Adam optimizer instead of SGD. Using Adam still gives me this error. Also, I tried to set the initial learning rate to 0.01, but still getting the error.
> 
> One other issue that I noticed is that, when I try to train the classification setting (only ResNet Backbone and main head) the Classification Error stays constant at 90% (using the default learning rate).

I noticed the same issues. For classification error,  I set 'cudnn.benchmark=False' in main.py, and found that the model can achieve about 9.5% classification error(±0.2) and 0.43 focal loss(±0.02).
